<a href="https://colab.research.google.com/github/Requell/data-science-bootcamp/blob/main/01_wprowadzenie/intro2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.__version__


'1.22.4'

In [ ]:
print(dir())

In [ ]:
help(np.array)

In [ ]:
x = np.array([1,3])
x

array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([1.3,2.3,1.4])
print(x)

[1.3 2.3 1.4]


In [ ]:
x.dtype

dtype('float64')

In [ ]:
x = np.array([[1,2],[-3,1]])
x

array([[ 1,  2],
       [-3,  1]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x = np.array([[1,2,4],[4,2,1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [ ]:
x = np.array(
    [[[4,3,1],
    [4,3,2]],

    [[4,1,3],
    [4,2,1]]]
     )
x

array([[[4, 3, 1],
        [4, 3, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape

(2, 2, 3)

In [ ]:
a =np.array([1,2,3])
a.dtype

dtype('int64')

In [ ]:
from numpy.core.multiarray import dtype
A = np.array([1,2,3], dtype='complex')
A.dtype

dtype('float64')

In [ ]:
A = np.array([1.0,2.7,3.3], dtype='int')
A.dtype

dtype('int64')

In [ ]:
A

array([1, 2, 3])

In [ ]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [ ]:
A = np.array([24, 128, 230], dtype=np.int8)
A.dtype

dtype('int8')

In [ ]:
A = np.array([24, 128, 230], dtype=np.uint8)
A.dtype

dtype('uint8')

In [ ]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones(shape=(5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [ ]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [ ]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((-1,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
A = np.array([3, 1, 4, 2])
B = np.array([3,-1,3,2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [ ]:
A+B

array([6, 0, 7, 4])

In [ ]:
A-B

array([0, 2, 1, 0])

In [ ]:
A*B

array([ 9, -1, 12,  4])

In [ ]:
A/B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
np.add(A,B)

array([6, 0, 7, 4])

In [ ]:
np.subtract(A,B)

array([0, 2, 1, 0])

In [ ]:
A +3

array([6, 4, 7, 5])

In [ ]:
np.multiply(A,B)

array([ 9, -1, 12,  4])

In [ ]:
np.divide(A,B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
2*A

array([6, 2, 8, 4])

In [ ]:
A+3*B

array([12, -2, 13,  8])

In [ ]:
X = np.array([[1,3],[-2,0]])
Y= np.array([[6,0],[-1,2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [ ]:
X*Y

array([[6, 0],
       [2, 0]])

In [ ]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
X @ Y

array([[  3,   6],
       [-12,   0]])

In [ ]:
np.random.seed(0)

In [ ]:
np.random.randn()

0.21514090731837932

In [ ]:
np.random.randn(10)

array([-0.36514421, -3.31342539, -0.13541682, -0.3946455 , -0.69937449,
        0.50139219,  0.84548578,  1.02784261, -0.03741391, -0.04011577])

In [ ]:
np.random.randn(10,4)

array([[-1.1675931 ,  1.24072478,  1.42956925, -0.9212017 ],
       [ 0.66319572,  1.76273473, -0.53791953,  0.84790658],
       [-0.30406314,  0.14791175, -0.17926211, -0.8199522 ],
       [ 1.24207383,  0.63284197, -1.17591543, -1.54271621],
       [-1.46493927, -0.25245125,  0.27192267, -0.67837935],
       [ 1.24630099, -1.12544684, -0.08950417,  2.48420124],
       [-0.59185363, -0.22360839, -1.0316849 , -0.18383426],
       [-0.61102079, -0.71651506, -1.39953821, -2.44697621],
       [-0.98744063,  1.44759432,  1.26592136, -1.81968334],
       [ 0.54886199, -0.6458226 ,  1.4621976 ,  0.41315756]])

In [ ]:
np.random.rand()

0.3330491054058723

In [ ]:
np.random.rand(10)

array([0.18233653, 0.76556093, 0.74502338, 0.58195542, 0.17462593,
       0.88144138, 0.41766767, 0.50547159, 0.34007513, 0.27265067])

In [ ]:
np.random.rand(10,2)

array([[0.82467367, 0.40687301],
       [0.73526572, 0.20414794],
       [0.63668471, 0.8460857 ],
       [0.71038405, 0.08621233],
       [0.8928634 , 0.33514508],
       [0.02532887, 0.28058203],
       [0.26720066, 0.32158132],
       [0.37709767, 0.26911689],
       [0.57008921, 0.23909638],
       [0.50817607, 0.48839708]])

In [ ]:
np.random.randint(10)

3

In [ ]:
np.random.randint(low=10, high=101)

74

In [ ]:
np.random.randint(low=10, high=101, size=10)

array([60, 38, 19, 41, 33, 21, 83, 21, 89, 16])

In [ ]:
np.random.choice([4,2,1,4])

4

In [ ]:
np.random.choice(['python', 'Java', 'SQL'])

'python'

In [ ]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(data)
data

array([6, 8, 0, 5, 4, 9, 7, 1, 3, 2])

In [ ]:
np.exp(1)

2.718281828459045

In [ ]:
np.sqrt(9)

3.0

In [ ]:
np.all([2,3,0])

False

In [ ]:
np.any([1,2,1])

True

In [ ]:
A = np.random.randn(5)
A

array([-1.27479615,  1.09540625, -1.06196055,  0.48432603, -0.15622982])

In [ ]:
np.argmax(A)

1

In [ ]:
A[np.argmax(A)]

1.0954062451824933

In [ ]:
np.argmin(A)

0

In [ ]:
np.argsort(A)

array([0, 2, 4, 3, 1])

In [ ]:
np.max(A)

1.0954062451824933

In [ ]:
np.min(A)

-1.2747961528547713

In [ ]:
np.median(A)

-0.15622982384861875

In [ ]:
np.std(A)

0.8994390571830544

In [ ]:
A =np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# A[idx], A[start:stop:], A[stop:], A[start:]

In [ ]:
A[2]

2

In [ ]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [ ]:
A[:2]

array([0, 1])

In [ ]:
A[[0,2]]

array([0, 2])

In [ ]:
A[-1]

19

In [ ]:
A[10:15]

array([10, 11, 12, 13, 14])

In [ ]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A[0]

array([0, 1, 2, 3, 4])

In [ ]:
A[:,0]

array([ 0,  5, 10, 15])

In [ ]:
A[:,-1]

array([ 4,  9, 14, 19])

In [ ]:
A[1,1]

6

In [ ]:
A[1,3]

8

In [ ]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [ ]:
A[1,2] =14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [7]:
import numpy as np


In [8]:
A =np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
A =A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [13]:
A[1,2] =14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [14]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [17]:
for row in A:
    print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [18]:
for row in A:
    print(row[0])

0
5
10
15


In [19]:
for row in A:
    print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [20]:
for item in A.flat:
    print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


In [21]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [22]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [23]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [24]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [26]:
A=np.arange(start=-10, stop=10, step=0.5)
A =A.reshape(10,-1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [27]:
A>0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [28]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [32]:
A[np.bitwise_and(A>-5,A<5)]


array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [34]:
np.bitwise_or(A<-5, A>5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])